language: cpp
install:
  - sudo pip install cpp-coveralls
script:
  - cmake .
  - make
  - ./unit_tests
after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*tests/.*.cpp.*"
